version: '3.7'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo16@2022
      POSTGRES_DB: odoo16
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo16"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - odoo-network
    restart: always

  odoo16:
    image: myodoo:16
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "10016:8069"
      - "20016:8072"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo16@2022
      DB_NAME: odoo16
      ODOO_CONF: /etc/odoo/odoo.conf
    volumes:
      - ./addons:/mnt/extra-addons
      - ./update_module_list.py:/scripts/update_module_list.py
      - ./etc:/etc/odoo
      - ./scripts:/scripts
      - ./logs:/var/log/odoo
    entrypoint: >
      bash -c "
      /scripts/wait-for-it.sh db:5432 --timeout=60 &&
      /entrypoint.sh odoo -d odoo16"
    networks:
      - odoo-network
    restart: always

volumes:
  postgres_data: {}

networks:
  odoo-network:
    driver: bridge
